### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by Bes79** [Stichoza/google-translate-php#112]
This error on all requests.

$str_tr = 'привет';
$tr = new Stichoza\GoogleTranslate\TranslateClient('en', 'ru');
$str_en = $tr->translate($str_tr);

print $str_en;

returns:

PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Client error: `POST https://translate.google.com/translate_a/single?client=t&hl=en&dt=t&sl=en&tl=ru&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=251610.386468` resulted in a `400 Bad Request` response:
<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=de (truncated...)
' in /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php:324
Stack trace:
#0 /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(361): Stichoza\GoogleTranslate\TranslateClient->getResponse('\xD0\xBF\xD1\x80\xD0\xB8\xD0\xB2\xD0\xB5\xD1\x82')
#1 /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(185): Stichoza\GoogleTranslate\TranslateClient->instanceTranslate('\xD0\xBF\xD1\x80\xD in /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php on line 324

**Comment by Bes79** [comment]
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Client error: `POST https://translate.google.com/translate_a/single?client=t&hl=en&dt=t&sl=en&tl=ru&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=251610.386468` resulted in a `400 Bad Request` response:
<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=de (truncated...)
' in /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php:324
Stack trace:
#0 /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(361): Stichoza\GoogleTranslate\TranslateClient->getResponse('\xD0\xBF\xD1\x80\xD0\xB8\xD0\xB2\xD0\xB5\xD1\x82')
#1 /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(185): Stichoza\GoogleTranslate\TranslateClient->instanceTranslate('\xD0\xBF\xD1\x80\xD in /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php on line 324

**Comment by Bes79** [comment]
`PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Client error: `POST https://translate.google.com/translate_a/single?client=t&hl=en&dt=t&sl=en&tl=ru&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=251610.386468` resulted in a `400 Bad Request` response:
<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=de (truncated...)
' in /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php:324
Stack trace:
#0 /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(361): Stichoza\GoogleTranslate\TranslateClient->getResponse('\xD0\xBF\xD1\x80\xD0\xB8\xD0\xB2\xD0\xB5\xD1\x82')
#1 /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(185): Stichoza\GoogleTranslate\TranslateClient->instanceTranslate('\xD0\xBF\xD1\x80\xD in /home/master/sites/dev2.rosmed.info/htdocs/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php on line 324
`

**Comment by yarekc** [comment]
Same issue..

**Comment by ederson13** [comment]
I have this issue since last week
I thought it was a problem on my side but i didn't have time to check it

**Comment by DerryIkhsan** [comment]
same issue ...

**Comment by dropshipdunas** [comment]
same problem here.

**Comment by anoire73** [comment]
same problem here.

**Comment by liamka** [comment]
Problem steel have

**Comment by frzsombor** [comment]
There is a pull request showing all the changes required to fix the issue.
Until the pull request gets merged you can make the changes directly.
Check: [#109 - Update GoogleTranslate.php (Files Changed)](https://github.com/Stichoza/google-translate-php/pull/109/files)

**Comment by Kollipso** [comment]
> There is a pull request showing all the changes required to fix the issue.
> Until the pull request gets merged you can make the changes directly.
> Check: [#109 - Update GoogleTranslate.php (Files Changed)](https://github.com/Stichoza/google-translate-php/pull/109/files)

It's works, thank you!

**Comment by Canadadry** [comment]
For those who have not the courage of forking I have for it with the fi from the PR 109 
Just `composer require canadadry/google-translate-php`

It will be deleted few weeks after the PR merged

**Comment by Stichoza** [comment]
Fixed in #109, pushed a new v4.0.2 tag

**Comment by gbelot2003** [comment]
is posible to apoint how to make the changes on old 3.6 version, is not working and imposible to upgrade to 7.1+ 
thaks

**Comment by nadia-am** [comment]
I am still having problem can any one help me?

`Fatal error: Uncaught ErrorException: Client error: `GET https://translate.google.com/translate_a/single?client=webapp&hl=en&dt=t&sl=fa&tl=en&tk=444888.64166&q=%3C%21--+wp%3Aheading+--%3E%3Ch2%3E%D9%85%D8%A7+%DA%A9%D9%87+%D9%87%D8%B3%D8%AA%DB%8C%D9%85%3C%2Fh2%3E%3C%21--+%2Fwp%3Aheading+--%3E%3C%21--+wp%3Aparagraph+--%3E%3Cp%3E%D9%86%D8%B4%D8%A7%D9%86%DB%8C+%D9%88%D8%A8%E2%80%8C%D8%B3%D8%A7%DB%8C%D8%AA+%D9%85%D8%A7%3A+http%3A%2F%2Fkhazar.mwteam.ir.%3C%2Fp%3E%3C%21--+%2Fwp%3Aparagraph+--%3E%3C%21--+wp%3Aheading+--%3E%3Ch2%3E%DA%A9%D8%AF%D8%A7%D9%85%DB%8C%DA%A9+%D8%A7%D8%B2+%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA+%D8%B4%D8%AE%D8%B5%DB%8C+%D8%B1%D8%A7+%D8%AC%D9%85%D8%B9+%D8%A2%D9%88%D8%B1%DB%8C+%D9%85%DB%8C%DA%A9%D9%86%DB%8C%D9%85+%D9%88+%DA%86%D8%B1%D8%A7%3C%2Fh2%3E%3C%21--+%2Fwp%3Aheading+--%3E%3C%21--+wp%3Aheading+%7B%22level%22%3A3%7D+--%3E%3Ch3%3E%D8%AF%DB%8C%D8%AF%DA%AF%D8%A7%D9%87%E2%80%8C%D9%87%D8%A7%3C%2Fh3%3E%3C%21--+%2Fwp%3Aheading+--%3E%3C%21--+wp%3Aparagraph+--%3E%3Cp%3E%D9%87%D9%86%DA%AF%D8%A7%D9%85%DB%8C+%DA in `
