### ISSUE TITLE
response change

### ISSUE THREAD

**Issue by natostanco** [Stichoza/google-translate-php#43]
Seems like the the response for string translations has changed a little and does not require array merging anymore since the string is returned as a whole, can someone confirm this?

`Warning: array_reduce() expects parameter 1 to be an array or collection in /../TranslateClient.php on line 333`

**Comment by tacbephot** [comment]
yes, me too
```
ErrorException in TranslateClient.php line 299:
Invalid argument supplied for foreach()
```

**Comment by tacbephot** [comment]
how can i fix it :(

**Comment by tacbephot** [comment]
aw..... i think i fixed it

by replace $detectedLanguages with

```
// Detect languages
        $detectedLanguages = [];
        $responseArrayForLanguages = ($isArray) ? $responseArray[0] : [$responseArray];
        foreach ($responseArrayForLanguages as $itemArray) {
                if (is_string($itemArray)) {
                    $detectedLanguages[] = $itemArray;
                }
        }

```

and bottom of function with

```
// Reduce array to generate translated sentenece
        if ($isArray) {
            $carry = [];
            foreach ($responseArray[0] as $item) {
                $carry[] = $item[0][0][0];
            }
            return $carry;
        } else {
            return $responseArray;
        }
```

**Comment by limonte** [comment]
Confirming this. By using `getResponse()` I'm getting now string with most popular translation. Until now it was an array with all translations. It seems that we have no ability to get all translations anymore :/

**Comment by pionl** [comment]
Still not working on latest version with this usage:
```
$translateClient = new TranslateClient();
$result = $translateClient->setSource($srcPrefix)->setTarget($fromPrefix)->translate($text);
```
API returns only translated text and the logic expects array. Added few detections to fix warnings and returned text. Tested on real application.

**Comment by stevebauman** [comment]
This is still an issue it seems:

```php
$googleTranslate = new TranslateClient();

$googleTranslate->setSource($parentTranslation->locale->code);
$googleTranslate->setTarget($locale->code);

$googleTranslate->translate('test');
```

Error:
```php
TranslateClient.php line 297:
Invalid argument supplied for foreach()
````
