### ISSUE TITLE
multiple sentence/array translation - error

### ISSUE THREAD

**Issue by nullcookies** [Stichoza/google-translate-php#65]
`<?php
//Composer Loader
$dir = realpath(**DIR**.'/');
require $dir.'/vendor/autoload.php';

use Stichoza\GoogleTranslate\TranslateClient;
$tr = new TranslateClient('en', 'ka');

var_dump ($tr->translate(['I can dance', 'I like trains', 'Double rainbow']));`

//output 
array (size=1)
  0 => string '�' (length=1)

help to correct?

**Comment by GaneshKandu** [comment]
I am also getting same Error out put as some ascii value
```php
<?php 

require 'vendor/autoload.php';
use Stichoza\GoogleTranslate\TranslateClient;

$tr = new TranslateClient('en', 'hi');
echo $tr->translate('Hello World!');
```
output
```
à¤¨à¤®à¤¸à¥à¤¤à¥‡ à¤¦à¥à¤¨à¤¿à¤¯à¤¾!
```

**Comment by geoffreyc** [comment]
Fixed in this PR:

https://github.com/Stichoza/google-translate-php/pull/88

**Comment by andrelopez** [comment]
Any update about this one? I'm still getting the same error.

Best,

**Comment by dejurin** [comment]
Array Not work

**Comment by Kutsenko-Andriy** [comment]
Yes, array not work 
`print_r($tr->translate(['I can dance', 'I like trains', 'Double rainbow']));`
Result:
Array ( [0] => � )

**Comment by dejurin** [comment]
Try this https://github.com/dejurin/php-google-translate-for-free

**Comment by laoman** [comment]
i am using the change from @geoffreyc works just fine
